# Generated by Django 3.0.7 on 2020-06-20 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='cretaed_at',
            new_name='created_at',
        ),
    ]
